<?php

namespace App\Http\Livewire\Admin\Advert;

use App\Http\Livewire\Admin\TableBase;
use App\Services\ExportService;
use App\Services\Resources\AdvertService;
use App\Services\Resources\RequestableService;
use App\Traits\WithRelationalSort;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Symfony\Component\HttpFoundation\StreamedResponse;

class Index extends TableBase
{
    use WithRelationalSort;

    //Advert specific filter criteria
    public string $status = 'all';
    public int|string $user_id = 0; // bugfix - |string is needed because input number is a string when empty
    public string $quantity_left = 'any'; //'any', 'done', 'in_progress', 'never_shown'

    protected $listeners = [
        'AdvertStatusChanged' => 'refresh',
    ];

    public function mount()
    {
        $this->sort_by = 'businessRequest.created_at';
        $this->sort_direction = 'DESC';
    }

    public function render(AdvertService $advertService)
    {
        $adverts = $this->getAdvertList($advertService);

        if ($this->global_sort == 'false') {
            $sortParams = $this->resolveSortByParameter($this->sort_by);
            $this->sortDisplayedPaginatorCollection($adverts, $sortParams);
        }

        return view('livewire.admin.advert.index', [
            'adverts' => $adverts,
        ]);
    }

    /**
     * Returns a paginated, filtered list of adverts or a searched through list of adverts if $this->search_query is set
     */
    public function getAdvertList(AdvertService $advertService): LengthAwarePaginator|Collection
    {
        return $advertService->getFilteredAdvertsPaginated(
            status: $this->status,
            user_id: $this->user_id == '' ? 0 : $this->user_id,
            quantity_left: $this->quantity_left,
            search_query: $this->search_query,
            do_sort: $this->global_sort == 'true',
            sort_by: $this->sort_by,
            sort_direction: $this->sort_direction,
            quantity: $this->quantity,
        );
    }

    /**
     * Exports the advert list to a CSV file
     * Returns a StreamedResponse with the CSV file
     * The CSV file is generated by the ExportService
     */
    public function export(ExportService $exportService, AdvertService $advertService, string $scope = 'displayed'): StreamedResponse
    {
        $data = ($scope == 'displayed')
            ? $this->getAdvertList($advertService)->values()->toArray()
            : $advertService->getFilteredAdvertsPaginated(quantity: 0)->toArray();

        $csv = $exportService->generateCSV($data, $advertService);

        return response()->streamDownload(function () use ($csv) {
            echo $csv;
        }, 'reklame' . now()->format('-d:m:Y') . '.csv');
    }

}



