<?php

namespace App\Http\Livewire\Admin\Advert;

use App\Http\Livewire\Admin\TableBase;
use App\Models\Advert;
use App\Services\AdvertService;
use App\Services\ExportService;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Livewire\Component;
use Livewire\WithPagination;
use Symfony\Component\HttpFoundation\StreamedResponse;

class Index extends TableBase
{
    protected $listeners = [
        'AdvertStatusChanged' => 'refresh',
    ];

    public function render(AdvertService $advertService)
    {
        $adverts = $this->getAdvertList($advertService);

        if ($this->global_sort == 'false') {
            $this->sortDisplayedAdvertList($adverts);
        }

        return view('livewire.admin.advert.index', [
            'adverts' => $adverts,
        ]);
    }

    /**
     * Returns a paginated, filtered list of adverts or a searched through list of adverts if $this->search_query is set
     */
    public function getAdvertList(AdvertService $advertService): LengthAwarePaginator|Collection
    {
        return new Collection();
    }

    /**
     * Sorts the movie list by $this->sort_by and $this->sort_direction
     * Only sorts the collection on the current page, doesn't change the LengthAwarePaginator $adverts
     */
    public function sortDisplayedAdvertList(&$adverts): void
    {
        $sorted = $adverts->getCollection()->sortBy(function ($movie, $key) {
            return $movie->{$this->sort_by};
        }, SORT_REGULAR, $this->sort_direction == 'DESC');

        $adverts->setCollection($sorted);
    }

    /**
     * Exports the advert list to a CSV file
     * Returns a StreamedResponse with the CSV file
     * The CSV file is generated by the ExportService
     */
    public function export(ExportService $exportService, AdvertService $advertService, string $scope = 'displayed'): StreamedResponse
    {
        $csv = 'aa';
        return response()->streamDownload(function () use ($csv) {
            echo $csv;
        }, 'filmovi' . now()->format('-d:m:Y') . '.csv');
    }

}



