<?php

namespace App\Http\Livewire\Admin\Movie;

use App\Http\Livewire\Admin\TableBase;
use App\Services\ExportService;
use App\Services\GenreService;
use App\Services\MovieService;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Symfony\Component\HttpFoundation\StreamedResponse;

class Index extends TableBase
{

    public $genres; //mounted
    public $genre = NULL;
    public $screening_time = "with past"; // 'any' 'now' 'tomorrow' 'week' 'with past'

    protected $listeners = [
        'MovieDeleted' => 'refresh',
    ];

    public function mount(GenreService $genreService): void
    {
        $this->genres = $genreService->getGenres();
    }

    public function render(MovieService $movieService)
    {
        $movies = $this->getMovieList($movieService);

        if ($this->global_sort == 'false') {
            $this->sortDisplayedMovieList($movies);
        }

        return view('livewire.admin.movie.index', [
            'movies' => $movies,
        ]);
    }

    /**
     * Returns a paginated, filtered list of movies or a searched through list of movies if $this->search_query is set
     */
    public function getMovieList(MovieService $movieService): LengthAwarePaginator|Collection
    {
        $genre = ($this->genre == NULL) ? NULL : [$this->genre];
        return ($this->search_query == '') ?
            $movieService->getFilteredMoviesPaginated(
                genres: $genre,
                screening_time: $this->screening_time,
                paginate: true,
                quantity: $this->quantity,
                do_sort: ($this->global_sort == 'true'),
                sort_by: $this->sort_by,
                sort_direction: $this->sort_direction
            ) :
            $movieService->getBySearch(
                search_query: $this->search_query,
                only_screening: false,
                paginate: true,
                quantity: $this->quantity,
                do_sort: ($this->global_sort == 'true'),
                sort_by: $this->sort_by,
                sort_direction: $this->sort_direction
            );
    }

    /**
     * Sorts the movie list by $this->sort_by and $this->sort_direction
     * Only sorts the collection on the current page, doesn't change the LengthAwarePaginator $movies
     */
    public function sortDisplayedMovieList(&$movies): void
    {
        $sorted = $movies->getCollection()->sortBy(function ($movie, $key) {
            return $movie->{$this->sort_by};
        }, SORT_REGULAR, $this->sort_direction == 'DESC');

        $movies->setCollection($sorted);
    }

    /**
     * Exports the movie list to a CSV file
     * Returns a StreamedResponse with the CSV file
     * The CSV file is generated by the ExportService
     */
    public function export(ExportService $exportService, MovieService $movieService, string $scope = 'displayed'): StreamedResponse
    {
        $data = ($scope == 'displayed')
            ? $this->getMovieList($movieService)->values()->toArray()
            : $movieService->getFilteredMoviesPaginated(screening_time: 'with_past');

        $csv = $exportService->generateCSV($data, $movieService);

        return response()->streamDownload(function () use ($csv) {
            echo $csv;
        }, 'filmovi' . now()->format('-d:m:Y') . '.csv');
    }

    /**
     * Emits event to open the delete modal
     */
    public function openDeleteModal(int $movie_id): void
    {
        $this->emitTo('admin.movie.delete-modal', 'showModal', $movie_id);
    }
}


